<a href="https://colab.research.google.com/github/eireford/ConwayLifeTensorFlow/blob/master/ConwayLifeTensorFlow_v4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

TensorFlow 2.x selected.


In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

In [0]:
import tensorflow as tf

In [0]:
import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

#np.set_printoptions(precision=4)

In [0]:
data_set_size = tf.constant([10_000],dtype=tf.int32)

In [0]:
life_density_kernal = tf.constant([1,1,1,1,10,1,1,1,1],dtype=tf.float32,name='life_density')
def alive(x):
  x1 = tf.multiply(x,life_density_kernal)
  x_sum = tf.reduce_sum(x1)
  return tf.cast(tf.where(((x_sum == 3)|(x_sum == 12)|(x_sum == 13)),1,0),dtype=tf.float32).numpy()

In [0]:
def get_data_examples(count=data_set_size):
  for i in range(count[0]):
    data_element = tf.round(tf.random.uniform([9],minval=0,maxval=1,dtype=tf.float32),name="data")
    label = alive(data_element)
    yield data_element[:],label

In [0]:
def get_data_set():
  data_gen = tf.data.Dataset.from_generator(get_data_examples,(tf.float32,tf.float32))

In [0]:
# %time get_data_set()

In [0]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [0]:
model1 = models.Sequential()
model1.add(layers.Dense(3, activation='relu', input_shape=(9,)))
model1.add(layers.Dense(1, activation='sigmoid'))
model1.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='mse',       # mean squared error
              metrics=['accuracy'])

In [0]:
model2 = models.Sequential()
model2.add(layers.Dense(3, activation='relu', input_shape=(9,)))
model2.add(layers.Dense(1, activation='sigmoid'))
model2.compile(optimizer=tf.keras.optimizers.Adam(0.003),
              loss='mse',       # mean squared error
              metrics=['accuracy'])

In [0]:
model3 = models.Sequential()
model3.add(layers.Dense(3, activation='relu', input_shape=(9,)))
model3.add(layers.Dense(1, activation='sigmoid'))
model3.compile(optimizer=tf.keras.optimizers.Adam(0.005),
              loss='mse',       # mean squared error
              metrics=['accuracy'])

In [0]:
dataset = tf.data.Dataset.from_generator(get_data_examples,(tf.float32,tf.float32),output_shapes=((9,),())) 

In [15]:
dataset1 = dataset.batch(1)
%time model1.fit(dataset1,epochs=10)

Epoch 1/10
10000/10000 [==============================] - 70s 7ms/step - loss: 0.1530 - accuracy: 0.7537
Epoch 2/10
10000/10000 [==============================] - 28s 3ms/step - loss: 0.0944 - accuracy: 0.8645
Epoch 3/10
10000/10000 [==============================] - 28s 3ms/step - loss: 0.0694 - accuracy: 0.9080
Epoch 4/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0658 - accuracy: 0.9134
Epoch 5/10
10000/10000 [==============================] - 28s 3ms/step - loss: 0.0674 - accuracy: 0.9097
Epoch 6/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0709 - accuracy: 0.9037
Epoch 7/10
10000/10000 [==============================] - 30s 3ms/step - loss: 0.0670 - accuracy: 0.9118
Epoch 8/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0688 - accuracy: 0.9087
Epoch 9/10
10000/10000 [==============================] - 28s 3ms/step - loss: 0.0692 - accuracy: 0.9078
Epoch 10/10
10000/10000 [==============================

In [16]:
dataset2 = dataset.batch(1)
%time model2.fit(dataset2,epochs=10)

Epoch 1/10
10000/10000 [==============================] - 69s 7ms/step - loss: 0.1181 - accuracy: 0.8403
Epoch 2/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0074 - accuracy: 1.0000
Epoch 3/10
10000/10000 [==============================] - 29s 3ms/step - loss: 6.7670e-05 - accuracy: 1.0000
Epoch 4/10
10000/10000 [==============================] - 29s 3ms/step - loss: 6.5509e-07 - accuracy: 1.0000
Epoch 5/10
10000/10000 [==============================] - 29s 3ms/step - loss: 1.0359e-08 - accuracy: 1.0000
Epoch 6/10
10000/10000 [==============================] - 29s 3ms/step - loss: 1.3570e-09 - accuracy: 1.0000
Epoch 7/10
10000/10000 [==============================] - 30s 3ms/step - loss: 6.6762e-10 - accuracy: 1.0000
Epoch 8/10
10000/10000 [==============================] - 29s 3ms/step - loss: 4.4402e-10 - accuracy: 1.0000
Epoch 9/10
10000/10000 [==============================] - 29s 3ms/step - loss: 3.1487e-10 - accuracy: 1.0000
Epoch 10/10
10000/10000 [==

In [17]:
dataset3 = dataset.batch(1)
%time model3.fit(dataset3,epochs=10)

Epoch 1/10
10000/10000 [==============================] - 72s 7ms/step - loss: 0.0939 - accuracy: 0.8604
Epoch 2/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0054 - accuracy: 0.9981
Epoch 3/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0012 - accuracy: 0.9985
Epoch 4/10
10000/10000 [==============================] - 29s 3ms/step - loss: 5.0970e-06 - accuracy: 1.0000
Epoch 5/10
10000/10000 [==============================] - 29s 3ms/step - loss: 0.0019 - accuracy: 0.9976
Epoch 6/10
10000/10000 [==============================] - 30s 3ms/step - loss: 6.0553e-07 - accuracy: 1.0000
Epoch 7/10
10000/10000 [==============================] - 29s 3ms/step - loss: 1.0681e-07 - accuracy: 1.0000
Epoch 8/10
10000/10000 [==============================] - 28s 3ms/step - loss: 3.4495e-04 - accuracy: 0.9995
Epoch 9/10
10000/10000 [==============================] - 29s 3ms/step - loss: 7.4464e-08 - accuracy: 1.0000
Epoch 10/10
10000/10000 [==========

In [0]:
test_set_size = tf.constant([100_000],dtype=tf.int32)

def get_test_examples(count=test_set_size):
  for i in range(count[0]):
    data_element = tf.round(tf.random.uniform([9],minval=0,maxval=1,dtype=tf.float32),name="data")
    label = alive(data_element)
    yield data_element[:],label

testset = tf.data.Dataset.from_generator(get_test_examples,(tf.float32,tf.float32),output_shapes=((9,),()))

In [19]:
testset1 = testset.batch(1000)
model1.evaluate(testset1)

    100/Unknown - 102s 1s/step - loss: 0.0682 - accuracy: 0.9091

[0.06816641557961703, 0.90911]

In [20]:
testset2 = testset.batch(1000)
model2.evaluate(testset2)

    100/Unknown - 102s 1s/step - loss: 2.3164e-10 - accuracy: 1.0000

[2.3164208232118179e-10, 1.0]

In [21]:
testset3 = testset.batch(1000)
model3.evaluate(testset3)

    100/Unknown - 101s 1s/step - loss: 4.3286e-09 - accuracy: 1.0000

[4.328610141435263e-09, 1.0]

In [0]:
testset_one= testset.batch(1)

In [23]:
counter = 0
for i in testset_one:
  counter += 1
  t = i
  #print(t[1])
  predicted = model1.predict(t)
  result = tf.reshape(tf.round(predicted),(1,))
  #tf.print(t,result,summarize=-1)
  equals = tf.equal(result,t[1])
  #print(equals)
  if tf.reduce_all(equals) == False:
    print("failed", t, predicted, result)
  if counter%1000 == 0: print("counting", counter)
print("done",counter)

failed (<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 1., 0., 0., 1.]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>) [[0.75322384]] tf.Tensor([1.], shape=(1,), dtype=float32)
failed (<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>) [[0.75322384]] tf.Tensor([1.], shape=(1,), dtype=float32)
failed (<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>) [[0.75322384]] tf.Tensor([1.], shape=(1,), dtype=float32)
failed (<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>) [[0.75322384]] tf.Tensor([1.], shape=(1,), dtype=float32)


In [24]:
counter = 0
for i in testset_one:
  counter += 1
  t = i
  #print(t[1])
  predicted = model2.predict(t)
  result = tf.reshape(tf.round(predicted),(1,))
  #tf.print(t,result,summarize=-1)
  equals = tf.equal(result,t[1])
  #print(equals)
  if tf.reduce_all(equals) == False:
    print("failed", t, predicted, result)
  if counter%1000 == 0: print("counting", counter)
print("done",counter)

counting 1000
counting 2000
counting 3000
counting 4000
counting 5000
counting 6000
counting 7000
counting 8000
counting 9000
counting 10000
counting 11000
counting 12000
counting 13000
counting 14000
counting 15000
counting 16000
counting 17000
counting 18000
counting 19000
counting 20000
counting 21000
counting 22000
counting 23000
counting 24000
counting 25000
counting 26000
counting 27000
counting 28000
counting 29000
counting 30000
counting 31000
counting 32000
counting 33000
counting 34000
counting 35000
counting 36000
counting 37000
counting 38000
counting 39000
counting 40000
counting 41000
counting 42000
counting 43000
counting 44000
counting 45000
counting 46000
counting 47000
counting 48000
counting 49000
counting 50000
counting 51000
counting 52000
counting 53000
counting 54000
counting 55000
counting 56000
counting 57000
counting 58000
counting 59000
counting 60000
counting 61000
counting 62000
counting 63000
counting 64000
counting 65000
counting 66000
counting 67000
coun

In [25]:
counter = 0
for i in testset_one:
  counter += 1
  t = i
  #print(t[1])
  predicted = model3.predict(t)
  result = tf.reshape(tf.round(predicted),(1,))
  #tf.print(t,result,summarize=-1)
  equals = tf.equal(result,t[1])
  #print(equals)
  if tf.reduce_all(equals) == False:
    print("failed", t, predicted, result)
  if counter%1000 == 0: print("counting", counter)
print("done",counter)

counting 1000
counting 2000
counting 3000
counting 4000
counting 5000
counting 6000
counting 7000
counting 8000
counting 9000
counting 10000
counting 11000
counting 12000
counting 13000
counting 14000
counting 15000
counting 16000
counting 17000
counting 18000
counting 19000
counting 20000
counting 21000
counting 22000
counting 23000
counting 24000
counting 25000
counting 26000
counting 27000
counting 28000
counting 29000
counting 30000
counting 31000
counting 32000
counting 33000
counting 34000
counting 35000
counting 36000
counting 37000
counting 38000
counting 39000
counting 40000
counting 41000
counting 42000
counting 43000
counting 44000
counting 45000
counting 46000
counting 47000
counting 48000
counting 49000
counting 50000
counting 51000
counting 52000
counting 53000
counting 54000
counting 55000
counting 56000
counting 57000
counting 58000
counting 59000
counting 60000
counting 61000
counting 62000
counting 63000
counting 64000
counting 65000
counting 66000
counting 67000
coun